[GLOBAL]
pants_version = "3.7.0"
backend_packages = [
  "pants.backend.experimental.go",
  "pants.backend.python",
  "pants.backend.build_files.fmt.black",
  "pants.backend.python.lint.black",
]

[source]
root_patterns = [
  '/src/python/BUILD',
]
